/**
 * Theme Configuration
 * Auto-generated by AppForge AI
 */

export const colors = {
  primary: {
  "50": "#FEF5F9",
  "100": "#FDECF4",
  "200": "#FAD1E5",
  "300": "#F7B5D6",
  "400": "#F17EB7",
  "500": "#EC4899",
  "600": "#D44089",
  "700": "#BC397A",
  "800": "#A5326B",
  "900": "#8D2B5B"
},
  secondary: {
  "50": "#F7F7F8",
  "100": "#F0F0F2",
  "200": "#DADBDF",
  "300": "#C3C6CC",
  "400": "#979CA6",
  "500": "#6B7280",
  "600": "#606673",
  "700": "#555B66",
  "800": "#4A4F59",
  "900": "#40444C"
},
  accent: {
  "50": "#FDF4F8",
  "100": "#FBE9F1",
  "200": "#F6C9DD",
  "300": "#F0A8C8",
  "400": "#E5679F",
  "500": "#DB2777",
  "600": "#C5236B",
  "700": "#AF1F5F",
  "800": "#991B53",
  "900": "#831747"
},
  neutral: {
  "50": "#FAFAFA",
  "100": "#F5F5F5",
  "200": "#E5E5E5",
  "300": "#D4D4D4",
  "400": "#A3A3A3",
  "500": "#737373",
  "600": "#525252",
  "700": "#404040",
  "800": "#262626",
  "900": "#171717"
},
  semantic: {
  "success": "#10B981",
  "warning": "#F59E0B",
  "error": "#EF4444",
  "info": "#3B82F6"
},
};

export const typography = {
  fontFamily: {
  "heading": "System",
  "body": "System",
  "mono": "Courier"
},
  scale: {
  "h1": {
    "fontSize": 32,
    "lineHeight": 40,
    "fontWeight": "700"
  },
  "h2": {
    "fontSize": 24,
    "lineHeight": 32,
    "fontWeight": "600"
  },
  "h3": {
    "fontSize": 20,
    "lineHeight": 28,
    "fontWeight": "600"
  },
  "h4": {
    "fontSize": 18,
    "lineHeight": 24,
    "fontWeight": "500"
  },
  "body": {
    "fontSize": 16,
    "lineHeight": 24,
    "fontWeight": "400"
  },
  "bodySmall": {
    "fontSize": 14,
    "lineHeight": 20,
    "fontWeight": "400"
  },
  "caption": {
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": "400"
  },
  "button": {
    "fontSize": 16,
    "lineHeight": 24,
    "fontWeight": "600"
  }
},
};

export const spacing = {
  base: 4,
  scale: [0,4,8,12,16,20,24,32,40,48,64],
};

export const animations = {
  duration: {
  "fast": 150,
  "normal": 300,
  "slow": 500
},
  easing: {
  "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "accelerate": "cubic-bezier(0.4, 0, 1, 1)",
  "decelerate": "cubic-bezier(0, 0, 0.2, 1)"
},
};

export default {
  colors,
  typography,
  spacing,
  animations,
};
